### ISSUE TITLE
No update sent to F5

### ISSUE THREAD

**Issue by kunalpuriii** [mdditt2000/kubernetes-1-19#1]
Hello Mark

I am following the procedure in the below link to implement CRD
https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.2/crd/big-ip-60-nodeport
However there is no configuration been sent to F5.

Do we need AS3 on the F5? if yes which version is required for this?
Also can this be used with the combination of AS3 and Ingress controller?

2020/11/26 12:56:34 [DEBUG] [CORE] NodePoller (0xc0002883f0) notifying listener: {l:0xc00004d740 s:0xc00004d7a0}
2020/11/26 12:56:34 [DEBUG] [CORE] NodePoller (0xc0002883f0) listener callback - num items: 2 err: <nil>
2020/11/26 12:56:35 [DEBUG] [2020-11-26 12:56:35,719 __main__ DEBUG] config handler woken for reset
2020/11/26 12:56:35 [DEBUG] [2020-11-26 12:56:35,720 __main__ DEBUG] loaded configuration file successfully
2020/11/26 12:56:35 [DEBUG] [2020-11-26 12:56:35,720 __main__ DEBUG] NET Config: {}
2020/11/26 12:56:35 [DEBUG] [2020-11-26 12:56:35,720 __main__ DEBUG] updating tasks finished, took 0.0005321502685546875 seconds
2020/11/26 12:57:04 [DEBUG] [CORE] NodePoller (0xc0002883f0) ready to poll, last wait: 30s

2020/11/26 12:57:04 [DEBUG] [CORE] NodePoller (0xc0002883f0) notifying listener: {l:0xc00004d740 s:0xc00004d7a0}
2020/11/26 12:57:04 [DEBUG] [CORE] NodePoller (0xc0002883f0) listener callback - num items: 2 err: <nil>
2020/11/26 12:57:05 [DEBUG] [2020-11-26 12:57:05,720 __main__ DEBUG] config handler woken for reset
2020/11/26 12:57:05 [DEBUG] [2020-11-26 12:57:05,720 __main__ DEBUG] loaded configuration file successfully
2020/11/26 12:57:05 [DEBUG] [2020-11-26 12:57:05,720 __main__ DEBUG] NET Config: {}
2020/11/26 12:57:05 [DEBUG] [2020-11-26 12:57:05,721 __main__ DEBUG] updating tasks finished, took 0.0008287429809570312 seconds

Looking forward to your response.

Thanks
Kunal

**Comment by mdditt2000** [comment]
@kunalpuriii Yes AS3 is the API required on BIG-IP
