### ISSUE TITLE
Transportserver no available member on pool use CRD 

### ISSUE THREAD

**Issue by quynhlab** [mdditt2000/kubernetes-1-19#3]
user@master1:~$ kubectl logs -f k8s-bigip-ctlr-deployment-546b5c7df5-nqrff -n kube-system | grep AS3
2021/11/23 01:57:00 [DEBUG] [AS3] PostManager Accepted the configuration
2021/11/23 01:57:00 [DEBUG] [AS3] posting request to https://10.163.15.66/mgmt/shared/appsvcs/declare/
2021/11/23 01:57:03 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:kubernetes --- message: success 

![image](https://user-images.githubusercontent.com/80056481/142960843-08b3ff27-afa6-422f-9122-3ede987202f5.png)

![image](https://user-images.githubusercontent.com/80056481/142960894-cca2cb56-9d8e-4af5-980e-a82a0ad4c6de.png)

**Comment by mdditt2000** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/pull/2103

I am awaiting an updated image. I should get an image tonight. Will send your way.

**Comment by quynhlab** [comment]
> thank you.

**Comment by mdditt2000** [comment]
Closing issue resolved
